version: "1.0"
info:
  model: int-scaffold
packages:
- name: RajniGitAZTESTProject
  gitServerName: RajniVC
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.rajnigitaztest.integrations:refenceDataTest
  packages:
  - name: RajniGitAZTESTProject
    version: "1.0"
- serviceName: project.rajnigitaztest.referencedata:refdata
  packages:
  - name: RajniGitAZTESTProject
    version: "1.0"
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
